Debug for `point_selection`, crashing due to API changes...
Did what the error was saying to correct:
ERROR LOG:
/home/jonathan/Softwares/vp/openalea-components/image/src/image/pil/ImageQt.pyc in __init__(self, im)
     67         elif im.mode == "RGBA":
     68             try:
---> 69                 data = im.tostring("raw", "BGRA")
     70             except SystemError:
     71                 # workaround for earlier versions

/usr/lib/python2.7/dist-packages/PIL/Image.pyc in tostring(self, *args, **kw)
    693     def tostring(self, *args, **kw):
    694         raise Exception("tostring() has been removed. " +
--> 695                         "Please call tobytes() instead.")
    696
    697     def tobitmap(self, name="image"):

Exception: tostring() has been removed. Please call tobytes() instead.